from typing import List, Optional
from loguru import logger
from backend.models import (
    GrimoireSnapshot, 
    GrimoireStateJSON, 
    ScribeExtractionResult,
    Entity
)

class ScribeApplier:
    """
    Applies the declarative ScribeExtractionResult delta JSON to a GrimoireSnapshot.
    Enforces the AGENT.md rules and SPEC definitions (like sliding memory arrays).
    """

    @staticmethod
    def apply_delta(
        current_snapshot: GrimoireSnapshot, 
        delta_result: ScribeExtractionResult,
        max_memory_items: int = 5
    ) -> GrimoireSnapshot:
        """
        Takes the current snapshot and a delta payload, returns a deeply cloned 
        and updated next-state Snapshot without mutating the original.
        """
        
        # Deep clone snapshot state using Pydantic
        old_state_dict = current_snapshot.grimoire_state_json.model_dump()
        new_state = GrimoireStateJSON.model_validate(old_state_dict)
        
        # Lookup Map
        entity_map = {e.entity_id: e for e in new_state.entities}

        for update in delta_result.updates:
            target_id = update.entity_id
            delta = update.delta
            
            if target_id not in entity_map:
                logger.warning(f"Scribe attempted to update unknown entity {target_id}")
                continue
                
            entity: Entity = entity_map[target_id]
            
            # 1. Health Delta
            if delta.health_delta is not None:
                entity.current_status.health = delta.health_delta
                
            # 2. Inventory Changes
            for added_item in delta.inventory_changes.added:
                if added_item not in entity.current_status.inventory:
                    entity.current_status.inventory.append(added_item)
            for removed_item in delta.inventory_changes.removed:
                if removed_item in entity.current_status.inventory:
                    entity.current_status.inventory.remove(removed_item)
                    
            # 3. Relationship Map
            for rel_id, rel_val in delta.relationship_changes.items():
                entity.current_status.relationships[rel_id] = rel_val
                
            # 4. Memory Sliding Window
            if delta.memory_to_append:
                memories = entity.current_status.recent_memory_summary
                memories.append(delta.memory_to_append)
                # Cap the sliding window
                if len(memories) > max_memory_items:
                    entity.current_status.recent_memory_summary = memories[-max_memory_items:]

        return GrimoireSnapshot(
            snapshot_id="placeholder_new_id", # Should be generated by caller
            branch_id=current_snapshot.branch_id,
            parent_snapshot_id=current_snapshot.snapshot_id,
            triggering_block_id="placeholder_block_id", # Should be generated by caller
            grimoire_state_json=new_state,
            created_at=current_snapshot.created_at # Re-assigned by caller
        )
