"""initial full schema

Revision ID: 26872b9f8b3d
Revises: 
Create Date: 2026-02-10 16:15:12.387567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '26872b9f8b3d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rank', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_rank'), 'chapters', ['rank'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('CHARACTER', 'LOCATION', 'ITEM', 'LORE', name='entitytype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('appearance_rank', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('disappearance_rank', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('disappearance_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_appearance_rank'), 'entities', ['appearance_rank'], unique=False)
    op.create_index(op.f('ix_entities_disappearance_rank'), 'entities', ['disappearance_rank'], unique=False)
    op.create_index(op.f('ix_entities_project_id'), 'entities', ['project_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('rank', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variants', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('selected_variant_index', sa.Integer(), nullable=False),
    sa.Column('content_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta_info', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_rank'), 'blocks', ['rank'], unique=False)
    op.create_table('entity_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_alias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_aliases_alias'), 'entity_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_entity_aliases_entity_id'), 'entity_aliases', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_aliases_normalized_alias'), 'entity_aliases', ['normalized_alias'], unique=False)
    op.create_table('entity_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_entity_id', sa.Integer(), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_rank', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_rank', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_relationships_category'), 'entity_relationships', ['category'], unique=False)
    op.create_index(op.f('ix_entity_relationships_end_rank'), 'entity_relationships', ['end_rank'], unique=False)
    op.create_index(op.f('ix_entity_relationships_start_rank'), 'entity_relationships', ['start_rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_relationships_start_rank'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_end_rank'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_category'), table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index(op.f('ix_entity_aliases_normalized_alias'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_entity_id'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_alias'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index(op.f('ix_blocks_rank'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_entities_project_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_disappearance_rank'), table_name='entities')
    op.drop_index(op.f('ix_entities_appearance_rank'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_chapters_rank'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
